"""empty message

Revision ID: 142a8a7c01f6
Revises: 1bb063a1b1e5
Create Date: 2016-03-29 14:25:55.392674

"""

# revision identifiers, used by Alembic.
revision = '142a8a7c01f6'
down_revision = '1bb063a1b1e5'

from alembic import op
import sqlalchemy as sa
import sil_fhir_server
from sqlalchemy import Column
from sil_fhir_server.data_types.primitives import StringField, IntegerField


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sil_fhir_server.data_types.primitives.IntegerField(), nullable=False),
    sa.Column('balance', sil_fhir_server.data_types.complex.pg_composite.CompositeType(
        'money_type', [
            Column('name', StringField()),
            Column('amount', IntegerField()),
            Column('smthn', StringField())]), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    ### end Alembic commands ###
