"""empty message

Revision ID: 5159eeb5aafe
Revises: 142a8a7c01f6
Create Date: 2016-03-29 16:27:15.799435

"""

# revision identifiers, used by Alembic.
revision = '5159eeb5aafe'
down_revision = '142a8a7c01f6'

from alembic import op
import sqlalchemy as sa
import sil_fhir_server
from sqlalchemy import Column
from sil_fhir_server.data_types.primitives import StringField, IntegerField


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_test',
    sa.Column('id', sil_fhir_server.data_types.primitives.IntegerField(), nullable=False),
    sa.Column('balance', sil_fhir_server.data_types.complex.pg_composite.CompositeType('money_type', [Column('name', StringField()), Column('amount', IntegerField()), Column('smthn', StringField())]), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_test')
    ### end Alembic commands ###
