"""empty message

Revision ID: 828789ded628
Revises: 5159eeb5aafe
Create Date: 2016-03-29 17:23:47.338494

"""

# revision identifiers, used by Alembic.
from app import connection
from sil_fhir_server.data_types.complex.pg_composite import register_composites

revision = '828789ded628'
down_revision = '5159eeb5aafe'

from alembic import op
import sqlalchemy as sa
import sil_fhir_server
from sqlalchemy import Column
from sil_fhir_server.data_types.primitives import StringField, IntegerField


register_composites(connection)
def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_test_me',
    sa.Column('id', sil_fhir_server.data_types.primitives.IntegerField(), nullable=False),
    sa.Column('balance', sil_fhir_server.data_types.complex.pg_composite.CompositeType('new_type', [Column('name', StringField()), Column('amount', IntegerField()), Column('smthn', StringField())]), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('account_test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='account_test_pkey')
    )
    op.drop_table('account_test_me')
    ### end Alembic commands ###
