"""empty message

Revision ID: fd834f38ddb6
Revises: 828789ded628
Create Date: 2011-01-01 12:30:15.286037

"""

# revision identifiers, used by Alembic.
revision = 'fd834f38ddb6'
down_revision = '828789ded628'

from alembic import op
import sqlalchemy as sa
import sil_fhir_server
from sqlalchemy import Column
from sil_fhir_server.data_types.primitives import StringField, IntegerField


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_to_test',
    sa.Column('id', sil_fhir_server.data_types.primitives.IntegerField(), nullable=False),
    sa.Column('balance', sil_fhir_server.data_types.complex.pg_composite.CompositeType('money_type', [Column('name', StringField(), table=None), Column('amount', IntegerField(), table=None), Column('smthn', StringField(), table=None)]), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('account_test_me')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_test_me',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='account_test_me_pkey')
    )
    op.drop_table('account_to_test')
    ### end Alembic commands ###
